package mk.ukim.finki.wp.baranja_oceni_prijavi.model;

public enum UserRole {
    STUDENT,
    PROFESSOR, ACADEMIC_AFFAIR_VICE_DEAN, SCIENCE_AND_COOPERATION_VICE_DEAN, FINANCES_VICE_DEAN, DEAN,
    STUDENT_ADMINISTRATION, FINANCE_ADMINISTRATION, LEGAL_ADMINISTRATION, ARCHIVE_ADMINISTRATION,
    EXTERNAL
}
